//
// Kbempgo Stor API

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: stor.proto

package kbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorAPI_GetDepsBy_FullMethodName  = "/kb.v1.StorAPI/GetDepsBy"
	StorAPI_GetSotrsBy_FullMethodName = "/kb.v1.StorAPI/GetSotrsBy"
	StorAPI_Flush_FullMethodName      = "/kb.v1.StorAPI/Flush"
	StorAPI_Save_FullMethodName       = "/kb.v1.StorAPI/Save"
	StorAPI_Update_FullMethodName     = "/kb.v1.StorAPI/Update"
	StorAPI_GetHistory_FullMethodName = "/kb.v1.StorAPI/GetHistory"
)

// StorAPIClient is the client API for StorAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stor service provides an interface to storage for kbemp data.
type StorAPIClient interface {
	// GetDep returns department data
	GetDepsBy(ctx context.Context, in *DepRequest, opts ...grpc.CallOption) (*DepsResponse, error)
	// GetSotr returns employee data by field
	GetSotrsBy(ctx context.Context, in *SotrRequest, opts ...grpc.CallOption) (*SotrsResponse, error)
	// Flush data
	// nolint:RPC_REQUEST_RESPONSE_UNIQUE
	Flush(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Save updates Dep data
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	Save(ctx context.Context, in *Item, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Update sotr if it exists by tabnum field
	// nolint:RPC_REQUEST_RESPONSE_UNIQUE
	Update(ctx context.Context, in *UpdateSotrRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get sotr history
	GetHistory(ctx context.Context, in *HistRequest, opts ...grpc.CallOption) (*HistoryListResponse, error)
}

type storAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewStorAPIClient(cc grpc.ClientConnInterface) StorAPIClient {
	return &storAPIClient{cc}
}

func (c *storAPIClient) GetDepsBy(ctx context.Context, in *DepRequest, opts ...grpc.CallOption) (*DepsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepsResponse)
	err := c.cc.Invoke(ctx, StorAPI_GetDepsBy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storAPIClient) GetSotrsBy(ctx context.Context, in *SotrRequest, opts ...grpc.CallOption) (*SotrsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SotrsResponse)
	err := c.cc.Invoke(ctx, StorAPI_GetSotrsBy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storAPIClient) Flush(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorAPI_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storAPIClient) Save(ctx context.Context, in *Item, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorAPI_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storAPIClient) Update(ctx context.Context, in *UpdateSotrRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorAPI_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storAPIClient) GetHistory(ctx context.Context, in *HistRequest, opts ...grpc.CallOption) (*HistoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryListResponse)
	err := c.cc.Invoke(ctx, StorAPI_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorAPIServer is the server API for StorAPI service.
// All implementations must embed UnimplementedStorAPIServer
// for forward compatibility.
//
// Stor service provides an interface to storage for kbemp data.
type StorAPIServer interface {
	// GetDep returns department data
	GetDepsBy(context.Context, *DepRequest) (*DepsResponse, error)
	// GetSotr returns employee data by field
	GetSotrsBy(context.Context, *SotrRequest) (*SotrsResponse, error)
	// Flush data
	// nolint:RPC_REQUEST_RESPONSE_UNIQUE
	Flush(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Save updates Dep data
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	Save(context.Context, *Item) (*emptypb.Empty, error)
	// Update sotr if it exists by tabnum field
	// nolint:RPC_REQUEST_RESPONSE_UNIQUE
	Update(context.Context, *UpdateSotrRequest) (*emptypb.Empty, error)
	// Get sotr history
	GetHistory(context.Context, *HistRequest) (*HistoryListResponse, error)
	mustEmbedUnimplementedStorAPIServer()
}

// UnimplementedStorAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorAPIServer struct{}

func (UnimplementedStorAPIServer) GetDepsBy(context.Context, *DepRequest) (*DepsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDepsBy not implemented")
}
func (UnimplementedStorAPIServer) GetSotrsBy(context.Context, *SotrRequest) (*SotrsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSotrsBy not implemented")
}
func (UnimplementedStorAPIServer) Flush(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedStorAPIServer) Save(context.Context, *Item) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedStorAPIServer) Update(context.Context, *UpdateSotrRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedStorAPIServer) GetHistory(context.Context, *HistRequest) (*HistoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedStorAPIServer) mustEmbedUnimplementedStorAPIServer() {}
func (UnimplementedStorAPIServer) testEmbeddedByValue()                 {}

// UnsafeStorAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorAPIServer will
// result in compilation errors.
type UnsafeStorAPIServer interface {
	mustEmbedUnimplementedStorAPIServer()
}

func RegisterStorAPIServer(s grpc.ServiceRegistrar, srv StorAPIServer) {
	// If the following call panics, it indicates UnimplementedStorAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorAPI_ServiceDesc, srv)
}

func _StorAPI_GetDepsBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorAPIServer).GetDepsBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorAPI_GetDepsBy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorAPIServer).GetDepsBy(ctx, req.(*DepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorAPI_GetSotrsBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SotrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorAPIServer).GetSotrsBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorAPI_GetSotrsBy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorAPIServer).GetSotrsBy(ctx, req.(*SotrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorAPI_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorAPIServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorAPI_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorAPIServer).Flush(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorAPI_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorAPIServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorAPI_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorAPIServer).Save(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorAPI_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSotrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorAPIServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorAPI_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorAPIServer).Update(ctx, req.(*UpdateSotrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorAPI_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorAPIServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorAPI_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorAPIServer).GetHistory(ctx, req.(*HistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorAPI_ServiceDesc is the grpc.ServiceDesc for StorAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kb.v1.StorAPI",
	HandlerType: (*StorAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDepsBy",
			Handler:    _StorAPI_GetDepsBy_Handler,
		},
		{
			MethodName: "GetSotrsBy",
			Handler:    _StorAPI_GetSotrsBy_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _StorAPI_Flush_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _StorAPI_Save_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StorAPI_Update_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _StorAPI_GetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stor.proto",
}
