//
// Kbempgo Stor API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: stor.proto

package kbv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Idr           string                 `protobuf:"bytes,2,opt,name=idr,proto3" json:"idr,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Children      bool                   `protobuf:"varint,5,opt,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dep) Reset() {
	*x = Dep{}
	mi := &file_stor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dep) ProtoMessage() {}

func (x *Dep) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dep.ProtoReflect.Descriptor instead.
func (*Dep) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{0}
}

func (x *Dep) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dep) GetIdr() string {
	if x != nil {
		return x.Idr
	}
	return ""
}

func (x *Dep) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Dep) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Dep) GetChildren() bool {
	if x != nil {
		return x.Children
	}
	return false
}

type Deps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deps          []*Dep                 `protobuf:"bytes,1,rep,name=Deps,proto3" json:"Deps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deps) Reset() {
	*x = Deps{}
	mi := &file_stor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deps) ProtoMessage() {}

func (x *Deps) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deps.ProtoReflect.Descriptor instead.
func (*Deps) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{1}
}

func (x *Deps) GetDeps() []*Dep {
	if x != nil {
		return x.Deps
	}
	return nil
}

type QueryString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           string                 `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryString) Reset() {
	*x = QueryString{}
	mi := &file_stor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryString) ProtoMessage() {}

func (x *QueryString) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryString.ProtoReflect.Descriptor instead.
func (*QueryString) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{2}
}

func (x *QueryString) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type Sotr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Idr           string                 `protobuf:"bytes,2,opt,name=idr,proto3" json:"idr,omitempty"`
	Tabnum        string                 `protobuf:"bytes,3,opt,name=tabnum,proto3" json:"tabnum,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	MidName       string                 `protobuf:"bytes,5,opt,name=mid_name,json=midName,proto3" json:"mid_name,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Mobile        string                 `protobuf:"bytes,7,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Grade         string                 `protobuf:"bytes,10,opt,name=grade,proto3" json:"grade,omitempty"`
	Children      bool                   `protobuf:"varint,11,opt,name=children,proto3" json:"children,omitempty"`
	ParentId      string                 `protobuf:"bytes,12,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Hist          []*History             `protobuf:"bytes,13,rep,name=hist,proto3" json:"hist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sotr) Reset() {
	*x = Sotr{}
	mi := &file_stor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sotr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sotr) ProtoMessage() {}

func (x *Sotr) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sotr.ProtoReflect.Descriptor instead.
func (*Sotr) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{3}
}

func (x *Sotr) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sotr) GetIdr() string {
	if x != nil {
		return x.Idr
	}
	return ""
}

func (x *Sotr) GetTabnum() string {
	if x != nil {
		return x.Tabnum
	}
	return ""
}

func (x *Sotr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sotr) GetMidName() string {
	if x != nil {
		return x.MidName
	}
	return ""
}

func (x *Sotr) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Sotr) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Sotr) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Sotr) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Sotr) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *Sotr) GetChildren() bool {
	if x != nil {
		return x.Children
	}
	return false
}

func (x *Sotr) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Sotr) GetHist() []*History {
	if x != nil {
		return x.Hist
	}
	return nil
}

type History struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	OldValue      string                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_stor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{4}
}

func (x *History) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *History) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *History) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

type Sotrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sotrs         []*Sotr                `protobuf:"bytes,1,rep,name=sotrs,proto3" json:"sotrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sotrs) Reset() {
	*x = Sotrs{}
	mi := &file_stor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sotrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sotrs) ProtoMessage() {}

func (x *Sotrs) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sotrs.ProtoReflect.Descriptor instead.
func (*Sotrs) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{5}
}

func (x *Sotrs) GetSotrs() []*Sotr {
	if x != nil {
		return x.Sotrs
	}
	return nil
}

var File_stor_proto protoreflect.FileDescriptor

const file_stor_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"stor.proto\x12\x05kb.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"o\n" +
	"\x03Dep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03idr\x18\x02 \x01(\tR\x03idr\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1a\n" +
	"\bchildren\x18\x05 \x01(\bR\bchildren\"&\n" +
	"\x04Deps\x12\x1e\n" +
	"\x04Deps\x18\x01 \x03(\v2\n" +
	".kb.v1.DepR\x04Deps\"\x1f\n" +
	"\vQueryString\x12\x10\n" +
	"\x03str\x18\x01 \x01(\tR\x03str\"\xc7\x02\n" +
	"\x04Sotr\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03idr\x18\x02 \x01(\tR\x03idr\x12\x16\n" +
	"\x06tabnum\x18\x03 \x01(\tR\x06tabnum\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x19\n" +
	"\bmid_name\x18\x05 \x01(\tR\amidName\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06mobile\x18\a \x01(\tR\x06mobile\x12\x1d\n" +
	"\x05email\x18\b \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatar\x12\x14\n" +
	"\x05grade\x18\n" +
	" \x01(\tR\x05grade\x12\x1a\n" +
	"\bchildren\x18\v \x01(\bR\bchildren\x12\x1b\n" +
	"\tparent_id\x18\f \x01(\tR\bparentId\x12\"\n" +
	"\x04hist\x18\r \x03(\v2\x0e.kb.v1.HistoryR\x04hist\"l\n" +
	"\aHistory\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\tR\boldValue\"*\n" +
	"\x05Sotrs\x12!\n" +
	"\x05sotrs\x18\x01 \x03(\v2\v.kb.v1.SotrR\x05sotrs2\xea\x03\n" +
	"\x04Stor\x12M\n" +
	"\vGetDepByIdr\x12\x12.kb.v1.QueryString\x1a\n" +
	".kb.v1.Dep\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/stor/v1/dep/{str}\x12^\n" +
	"\x0fGetSotrByTabnum\x12\x12.kb.v1.QueryString\x1a\v.kb.v1.Sotr\"*\x82\xd3\xe4\x93\x02$\x12\"/api/stor/v1/employee/tabnum/{str}\x12X\n" +
	"\fGetSotrByFio\x12\x12.kb.v1.QueryString\x1a\v.kb.v1.Sotr\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/stor/v1/employee/fio/{str}\x12_\n" +
	"\x0fGetSotrByMobile\x12\x12.kb.v1.QueryString\x1a\f.kb.v1.Sotrs\"*\x82\xd3\xe4\x93\x02$\x12\"/api/stor/v1/employee/mobile/{str}\x12x\n" +
	"\x04Save\x12\n" +
	".kb.v1.Dep\x1a\x16.google.protobuf.Empty\"L\x82\xd3\xe4\x93\x02F:\x01*Z\x16:\x01*\x1a\x11/api/stor/v1/saveZ\x16:\x01*2\x11/api/stor/v1/save\"\x11/api/stor/v1/saveB-Z+github.com/mioxin/kbempgo/api/kbemp/v1;kbv1b\x06proto3"

var (
	file_stor_proto_rawDescOnce sync.Once
	file_stor_proto_rawDescData []byte
)

func file_stor_proto_rawDescGZIP() []byte {
	file_stor_proto_rawDescOnce.Do(func() {
		file_stor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stor_proto_rawDesc), len(file_stor_proto_rawDesc)))
	})
	return file_stor_proto_rawDescData
}

var file_stor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stor_proto_goTypes = []any{
	(*Dep)(nil),                   // 0: kb.v1.Dep
	(*Deps)(nil),                  // 1: kb.v1.Deps
	(*QueryString)(nil),           // 2: kb.v1.QueryString
	(*Sotr)(nil),                  // 3: kb.v1.Sotr
	(*History)(nil),               // 4: kb.v1.History
	(*Sotrs)(nil),                 // 5: kb.v1.Sotrs
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_stor_proto_depIdxs = []int32{
	0, // 0: kb.v1.Deps.Deps:type_name -> kb.v1.Dep
	4, // 1: kb.v1.Sotr.hist:type_name -> kb.v1.History
	6, // 2: kb.v1.History.date:type_name -> google.protobuf.Timestamp
	3, // 3: kb.v1.Sotrs.sotrs:type_name -> kb.v1.Sotr
	2, // 4: kb.v1.Stor.GetDepByIdr:input_type -> kb.v1.QueryString
	2, // 5: kb.v1.Stor.GetSotrByTabnum:input_type -> kb.v1.QueryString
	2, // 6: kb.v1.Stor.GetSotrByFio:input_type -> kb.v1.QueryString
	2, // 7: kb.v1.Stor.GetSotrByMobile:input_type -> kb.v1.QueryString
	0, // 8: kb.v1.Stor.Save:input_type -> kb.v1.Dep
	0, // 9: kb.v1.Stor.GetDepByIdr:output_type -> kb.v1.Dep
	3, // 10: kb.v1.Stor.GetSotrByTabnum:output_type -> kb.v1.Sotr
	3, // 11: kb.v1.Stor.GetSotrByFio:output_type -> kb.v1.Sotr
	5, // 12: kb.v1.Stor.GetSotrByMobile:output_type -> kb.v1.Sotrs
	7, // 13: kb.v1.Stor.Save:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_stor_proto_init() }
func file_stor_proto_init() {
	if File_stor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stor_proto_rawDesc), len(file_stor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stor_proto_goTypes,
		DependencyIndexes: file_stor_proto_depIdxs,
		MessageInfos:      file_stor_proto_msgTypes,
	}.Build()
	File_stor_proto = out.File
	file_stor_proto_goTypes = nil
	file_stor_proto_depIdxs = nil
}
