// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: stor.proto

package kbv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Dep with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Dep) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Dep with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DepMultiError, or nil if none found.
func (m *Dep) ValidateAll() error {
	return m.validate(true)
}

func (m *Dep) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Idr

	// no validation rules for Parent

	// no validation rules for Text

	// no validation rules for Children

	if len(errors) > 0 {
		return DepMultiError(errors)
	}

	return nil
}

// DepMultiError is an error wrapping multiple validation errors returned by
// Dep.ValidateAll() if the designated constraints aren't met.
type DepMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepMultiError) AllErrors() []error { return m }

// DepValidationError is the validation error returned by Dep.Validate if the
// designated constraints aren't met.
type DepValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepValidationError) ErrorName() string { return "DepValidationError" }

// Error satisfies the builtin error interface
func (e DepValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDep.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepValidationError{}

// Validate checks the field values on DepsResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DepsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DepsResponseMultiError, or
// nil if none found.
func (m *DepsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DepsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDeps() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DepsResponseValidationError{
						field:  fmt.Sprintf("Deps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DepsResponseValidationError{
						field:  fmt.Sprintf("Deps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DepsResponseValidationError{
					field:  fmt.Sprintf("Deps[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DepsResponseMultiError(errors)
	}

	return nil
}

// DepsResponseMultiError is an error wrapping multiple validation errors
// returned by DepsResponse.ValidateAll() if the designated constraints aren't met.
type DepsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepsResponseMultiError) AllErrors() []error { return m }

// DepsResponseValidationError is the validation error returned by
// DepsResponse.Validate if the designated constraints aren't met.
type DepsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepsResponseValidationError) ErrorName() string { return "DepsResponseValidationError" }

// Error satisfies the builtin error interface
func (e DepsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepsResponseValidationError{}

// Validate checks the field values on DepRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DepRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DepRequestMultiError, or
// nil if none found.
func (m *DepRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DepRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Str

	// no validation rules for Field

	if len(errors) > 0 {
		return DepRequestMultiError(errors)
	}

	return nil
}

// DepRequestMultiError is an error wrapping multiple validation errors
// returned by DepRequest.ValidateAll() if the designated constraints aren't met.
type DepRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepRequestMultiError) AllErrors() []error { return m }

// DepRequestValidationError is the validation error returned by
// DepRequest.Validate if the designated constraints aren't met.
type DepRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepRequestValidationError) ErrorName() string { return "DepRequestValidationError" }

// Error satisfies the builtin error interface
func (e DepRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepRequestValidationError{}

// Validate checks the field values on SotrRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SotrRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SotrRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SotrRequestMultiError, or
// nil if none found.
func (m *SotrRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SotrRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Str

	// no validation rules for Field

	if len(errors) > 0 {
		return SotrRequestMultiError(errors)
	}

	return nil
}

// SotrRequestMultiError is an error wrapping multiple validation errors
// returned by SotrRequest.ValidateAll() if the designated constraints aren't met.
type SotrRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SotrRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SotrRequestMultiError) AllErrors() []error { return m }

// SotrRequestValidationError is the validation error returned by
// SotrRequest.Validate if the designated constraints aren't met.
type SotrRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SotrRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SotrRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SotrRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SotrRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SotrRequestValidationError) ErrorName() string { return "SotrRequestValidationError" }

// Error satisfies the builtin error interface
func (e SotrRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSotrRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SotrRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SotrRequestValidationError{}

// Validate checks the field values on HistRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HistRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HistRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HistRequestMultiError, or
// nil if none found.
func (m *HistRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HistRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SotrId

	if len(errors) > 0 {
		return HistRequestMultiError(errors)
	}

	return nil
}

// HistRequestMultiError is an error wrapping multiple validation errors
// returned by HistRequest.ValidateAll() if the designated constraints aren't met.
type HistRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HistRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HistRequestMultiError) AllErrors() []error { return m }

// HistRequestValidationError is the validation error returned by
// HistRequest.Validate if the designated constraints aren't met.
type HistRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HistRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HistRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HistRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HistRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HistRequestValidationError) ErrorName() string { return "HistRequestValidationError" }

// Error satisfies the builtin error interface
func (e HistRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHistRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HistRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HistRequestValidationError{}

// Validate checks the field values on Sotr with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Sotr) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Sotr with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SotrMultiError, or nil if none found.
func (m *Sotr) ValidateAll() error {
	return m.validate(true)
}

func (m *Sotr) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Idr

	// no validation rules for Tabnum

	// no validation rules for Name

	// no validation rules for MidName

	if m.GetEmail() != "" {

		if err := m._validateEmail(m.GetEmail()); err != nil {
			err = SotrValidationError{
				field:  "Email",
				reason: "value must be a valid email address",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for Avatar

	// no validation rules for Grade

	// no validation rules for Children

	// no validation rules for ParentId

	if all {
		switch v := interface{}(m.GetDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SotrValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SotrValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SotrValidationError{
				field:  "Date",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SotrMultiError(errors)
	}

	return nil
}

func (m *Sotr) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *Sotr) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// SotrMultiError is an error wrapping multiple validation errors returned by
// Sotr.ValidateAll() if the designated constraints aren't met.
type SotrMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SotrMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SotrMultiError) AllErrors() []error { return m }

// SotrValidationError is the validation error returned by Sotr.Validate if the
// designated constraints aren't met.
type SotrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SotrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SotrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SotrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SotrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SotrValidationError) ErrorName() string { return "SotrValidationError" }

// Error satisfies the builtin error interface
func (e SotrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSotr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SotrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SotrValidationError{}

// Validate checks the field values on History with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *History) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on History with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HistoryMultiError, or nil if none found.
func (m *History) ValidateAll() error {
	return m.validate(true)
}

func (m *History) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, HistoryValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, HistoryValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HistoryValidationError{
				field:  "Date",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Field

	// no validation rules for OldValue

	// no validation rules for SotrId

	if len(errors) > 0 {
		return HistoryMultiError(errors)
	}

	return nil
}

// HistoryMultiError is an error wrapping multiple validation errors returned
// by History.ValidateAll() if the designated constraints aren't met.
type HistoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HistoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HistoryMultiError) AllErrors() []error { return m }

// HistoryValidationError is the validation error returned by History.Validate
// if the designated constraints aren't met.
type HistoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HistoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HistoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HistoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HistoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HistoryValidationError) ErrorName() string { return "HistoryValidationError" }

// Error satisfies the builtin error interface
func (e HistoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHistory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HistoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HistoryValidationError{}

// Validate checks the field values on SotrsResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SotrsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SotrsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SotrsResponseMultiError, or
// nil if none found.
func (m *SotrsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SotrsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSotrs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SotrsResponseValidationError{
						field:  fmt.Sprintf("Sotrs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SotrsResponseValidationError{
						field:  fmt.Sprintf("Sotrs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SotrsResponseValidationError{
					field:  fmt.Sprintf("Sotrs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SotrsResponseMultiError(errors)
	}

	return nil
}

// SotrsResponseMultiError is an error wrapping multiple validation errors
// returned by SotrsResponse.ValidateAll() if the designated constraints
// aren't met.
type SotrsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SotrsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SotrsResponseMultiError) AllErrors() []error { return m }

// SotrsResponseValidationError is the validation error returned by
// SotrsResponse.Validate if the designated constraints aren't met.
type SotrsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SotrsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SotrsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SotrsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SotrsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SotrsResponseValidationError) ErrorName() string { return "SotrsResponseValidationError" }

// Error satisfies the builtin error interface
func (e SotrsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSotrsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SotrsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SotrsResponseValidationError{}

// Validate checks the field values on Item with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Item with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ItemMultiError, or nil if none found.
func (m *Item) ValidateAll() error {
	return m.validate(true)
}

func (m *Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Var.(type) {
	case *Item_Dep:
		if v == nil {
			err := ItemValidationError{
				field:  "Var",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDep()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ItemValidationError{
						field:  "Dep",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ItemValidationError{
						field:  "Dep",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDep()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemValidationError{
					field:  "Dep",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Item_Sotr:
		if v == nil {
			err := ItemValidationError{
				field:  "Var",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSotr()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ItemValidationError{
						field:  "Sotr",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ItemValidationError{
						field:  "Sotr",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSotr()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemValidationError{
					field:  "Sotr",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ItemMultiError(errors)
	}

	return nil
}

// ItemMultiError is an error wrapping multiple validation errors returned by
// Item.ValidateAll() if the designated constraints aren't met.
type ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ItemMultiError) AllErrors() []error { return m }

// ItemValidationError is the validation error returned by Item.Validate if the
// designated constraints aren't met.
type ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ItemValidationError) ErrorName() string { return "ItemValidationError" }

// Error satisfies the builtin error interface
func (e ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ItemValidationError{}

// Validate checks the field values on HistoryListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HistoryListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HistoryListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HistoryListResponseMultiError, or nil if none found.
func (m *HistoryListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HistoryListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetHistoryList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HistoryListResponseValidationError{
						field:  fmt.Sprintf("HistoryList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HistoryListResponseValidationError{
						field:  fmt.Sprintf("HistoryList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HistoryListResponseValidationError{
					field:  fmt.Sprintf("HistoryList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HistoryListResponseMultiError(errors)
	}

	return nil
}

// HistoryListResponseMultiError is an error wrapping multiple validation
// errors returned by HistoryListResponse.ValidateAll() if the designated
// constraints aren't met.
type HistoryListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HistoryListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HistoryListResponseMultiError) AllErrors() []error { return m }

// HistoryListResponseValidationError is the validation error returned by
// HistoryListResponse.Validate if the designated constraints aren't met.
type HistoryListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HistoryListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HistoryListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HistoryListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HistoryListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HistoryListResponseValidationError) ErrorName() string {
	return "HistoryListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HistoryListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHistoryListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HistoryListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HistoryListResponseValidationError{}

// Validate checks the field values on UpdateSotrRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateSotrRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSotrRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateSotrRequestMultiError, or nil if none found.
func (m *UpdateSotrRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSotrRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSotr()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateSotrRequestValidationError{
					field:  "Sotr",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateSotrRequestValidationError{
					field:  "Sotr",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSotr()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateSotrRequestValidationError{
				field:  "Sotr",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetHistoryList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UpdateSotrRequestValidationError{
						field:  fmt.Sprintf("HistoryList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UpdateSotrRequestValidationError{
						field:  fmt.Sprintf("HistoryList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UpdateSotrRequestValidationError{
					field:  fmt.Sprintf("HistoryList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UpdateSotrRequestMultiError(errors)
	}

	return nil
}

// UpdateSotrRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateSotrRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateSotrRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSotrRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSotrRequestMultiError) AllErrors() []error { return m }

// UpdateSotrRequestValidationError is the validation error returned by
// UpdateSotrRequest.Validate if the designated constraints aren't met.
type UpdateSotrRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSotrRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSotrRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSotrRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSotrRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSotrRequestValidationError) ErrorName() string {
	return "UpdateSotrRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSotrRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSotrRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSotrRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSotrRequestValidationError{}
