//
// Kbempgo Stor API

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: stor.proto

package kbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stor_GetDepBy_FullMethodName        = "/kb.v1.Stor/GetDepBy"
	Stor_GetSotrByTabnum_FullMethodName = "/kb.v1.Stor/GetSotrByTabnum"
	Stor_GetSotrByFio_FullMethodName    = "/kb.v1.Stor/GetSotrByFio"
	Stor_Save_FullMethodName            = "/kb.v1.Stor/Save"
)

// StorClient is the client API for Stor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stor service provides an interface to storage for kbemp data.
type StorClient interface {
	// GetDep returns department data
	GetDepBy(ctx context.Context, in *Idr, opts ...grpc.CallOption) (*Item, error)
	// GetSotr returns employee data
	GetSotrByTabnum(ctx context.Context, in *Tabnum, opts ...grpc.CallOption) (*Sotr, error)
	GetSotrByFio(ctx context.Context, in *Fio, opts ...grpc.CallOption) (*Sotr, error)
	// Save updates Item data
	Save(ctx context.Context, in *Item, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type storClient struct {
	cc grpc.ClientConnInterface
}

func NewStorClient(cc grpc.ClientConnInterface) StorClient {
	return &storClient{cc}
}

func (c *storClient) GetDepBy(ctx context.Context, in *Idr, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, Stor_GetDepBy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storClient) GetSotrByTabnum(ctx context.Context, in *Tabnum, opts ...grpc.CallOption) (*Sotr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sotr)
	err := c.cc.Invoke(ctx, Stor_GetSotrByTabnum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storClient) GetSotrByFio(ctx context.Context, in *Fio, opts ...grpc.CallOption) (*Sotr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sotr)
	err := c.cc.Invoke(ctx, Stor_GetSotrByFio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storClient) Save(ctx context.Context, in *Item, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Stor_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorServer is the server API for Stor service.
// All implementations must embed UnimplementedStorServer
// for forward compatibility.
//
// Stor service provides an interface to storage for kbemp data.
type StorServer interface {
	// GetDep returns department data
	GetDepBy(context.Context, *Idr) (*Item, error)
	// GetSotr returns employee data
	GetSotrByTabnum(context.Context, *Tabnum) (*Sotr, error)
	GetSotrByFio(context.Context, *Fio) (*Sotr, error)
	// Save updates Item data
	Save(context.Context, *Item) (*emptypb.Empty, error)
	mustEmbedUnimplementedStorServer()
}

// UnimplementedStorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorServer struct{}

func (UnimplementedStorServer) GetDepBy(context.Context, *Idr) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepBy not implemented")
}
func (UnimplementedStorServer) GetSotrByTabnum(context.Context, *Tabnum) (*Sotr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSotrByTabnum not implemented")
}
func (UnimplementedStorServer) GetSotrByFio(context.Context, *Fio) (*Sotr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSotrByFio not implemented")
}
func (UnimplementedStorServer) Save(context.Context, *Item) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedStorServer) mustEmbedUnimplementedStorServer() {}
func (UnimplementedStorServer) testEmbeddedByValue()              {}

// UnsafeStorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorServer will
// result in compilation errors.
type UnsafeStorServer interface {
	mustEmbedUnimplementedStorServer()
}

func RegisterStorServer(s grpc.ServiceRegistrar, srv StorServer) {
	// If the following call pancis, it indicates UnimplementedStorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stor_ServiceDesc, srv)
}

func _Stor_GetDepBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Idr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorServer).GetDepBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stor_GetDepBy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorServer).GetDepBy(ctx, req.(*Idr))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stor_GetSotrByTabnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tabnum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorServer).GetSotrByTabnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stor_GetSotrByTabnum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorServer).GetSotrByTabnum(ctx, req.(*Tabnum))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stor_GetSotrByFio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Fio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorServer).GetSotrByFio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stor_GetSotrByFio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorServer).GetSotrByFio(ctx, req.(*Fio))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stor_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stor_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorServer).Save(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

// Stor_ServiceDesc is the grpc.ServiceDesc for Stor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kb.v1.Stor",
	HandlerType: (*StorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDepBy",
			Handler:    _Stor_GetDepBy_Handler,
		},
		{
			MethodName: "GetSotrByTabnum",
			Handler:    _Stor_GetSotrByTabnum_Handler,
		},
		{
			MethodName: "GetSotrByFio",
			Handler:    _Stor_GetSotrByFio_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Stor_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stor.proto",
}
