// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: stor.proto

package kbv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Dep with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Dep) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Dep with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DepMultiError, or nil if none found.
func (m *Dep) ValidateAll() error {
	return m.validate(true)
}

func (m *Dep) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Idr

	// no validation rules for Parent

	// no validation rules for Text

	// no validation rules for Children

	if len(errors) > 0 {
		return DepMultiError(errors)
	}

	return nil
}

// DepMultiError is an error wrapping multiple validation errors returned by
// Dep.ValidateAll() if the designated constraints aren't met.
type DepMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepMultiError) AllErrors() []error { return m }

// DepValidationError is the validation error returned by Dep.Validate if the
// designated constraints aren't met.
type DepValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepValidationError) ErrorName() string { return "DepValidationError" }

// Error satisfies the builtin error interface
func (e DepValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDep.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepValidationError{}

// Validate checks the field values on Deps with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Deps) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Deps with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DepsMultiError, or nil if none found.
func (m *Deps) ValidateAll() error {
	return m.validate(true)
}

func (m *Deps) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDeps() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DepsValidationError{
						field:  fmt.Sprintf("Deps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DepsValidationError{
						field:  fmt.Sprintf("Deps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DepsValidationError{
					field:  fmt.Sprintf("Deps[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DepsMultiError(errors)
	}

	return nil
}

// DepsMultiError is an error wrapping multiple validation errors returned by
// Deps.ValidateAll() if the designated constraints aren't met.
type DepsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepsMultiError) AllErrors() []error { return m }

// DepsValidationError is the validation error returned by Deps.Validate if the
// designated constraints aren't met.
type DepsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepsValidationError) ErrorName() string { return "DepsValidationError" }

// Error satisfies the builtin error interface
func (e DepsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeps.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepsValidationError{}

// Validate checks the field values on QueryDep with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QueryDep) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryDep with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QueryDepMultiError, or nil
// if none found.
func (m *QueryDep) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryDep) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Str

	// no validation rules for Field

	if len(errors) > 0 {
		return QueryDepMultiError(errors)
	}

	return nil
}

// QueryDepMultiError is an error wrapping multiple validation errors returned
// by QueryDep.ValidateAll() if the designated constraints aren't met.
type QueryDepMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryDepMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryDepMultiError) AllErrors() []error { return m }

// QueryDepValidationError is the validation error returned by
// QueryDep.Validate if the designated constraints aren't met.
type QueryDepValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryDepValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryDepValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryDepValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryDepValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryDepValidationError) ErrorName() string { return "QueryDepValidationError" }

// Error satisfies the builtin error interface
func (e QueryDepValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryDep.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryDepValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryDepValidationError{}

// Validate checks the field values on QuerySotr with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QuerySotr) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QuerySotr with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QuerySotrMultiError, or nil
// if none found.
func (m *QuerySotr) ValidateAll() error {
	return m.validate(true)
}

func (m *QuerySotr) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Str

	// no validation rules for Field

	if len(errors) > 0 {
		return QuerySotrMultiError(errors)
	}

	return nil
}

// QuerySotrMultiError is an error wrapping multiple validation errors returned
// by QuerySotr.ValidateAll() if the designated constraints aren't met.
type QuerySotrMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QuerySotrMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QuerySotrMultiError) AllErrors() []error { return m }

// QuerySotrValidationError is the validation error returned by
// QuerySotr.Validate if the designated constraints aren't met.
type QuerySotrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuerySotrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuerySotrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuerySotrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuerySotrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuerySotrValidationError) ErrorName() string { return "QuerySotrValidationError" }

// Error satisfies the builtin error interface
func (e QuerySotrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuerySotr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuerySotrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuerySotrValidationError{}

// Validate checks the field values on QueryHist with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QueryHist) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryHist with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QueryHistMultiError, or nil
// if none found.
func (m *QueryHist) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryHist) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SotrId

	if len(errors) > 0 {
		return QueryHistMultiError(errors)
	}

	return nil
}

// QueryHistMultiError is an error wrapping multiple validation errors returned
// by QueryHist.ValidateAll() if the designated constraints aren't met.
type QueryHistMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryHistMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryHistMultiError) AllErrors() []error { return m }

// QueryHistValidationError is the validation error returned by
// QueryHist.Validate if the designated constraints aren't met.
type QueryHistValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryHistValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryHistValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryHistValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryHistValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryHistValidationError) ErrorName() string { return "QueryHistValidationError" }

// Error satisfies the builtin error interface
func (e QueryHistValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryHist.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryHistValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryHistValidationError{}

// Validate checks the field values on Sotr with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Sotr) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Sotr with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SotrMultiError, or nil if none found.
func (m *Sotr) ValidateAll() error {
	return m.validate(true)
}

func (m *Sotr) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Idr

	// no validation rules for Tabnum

	// no validation rules for Name

	// no validation rules for MidName

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = SotrValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Avatar

	// no validation rules for Grade

	// no validation rules for Children

	// no validation rules for ParentId

	if all {
		switch v := interface{}(m.GetDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SotrValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SotrValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SotrValidationError{
				field:  "Date",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SotrMultiError(errors)
	}

	return nil
}

func (m *Sotr) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *Sotr) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// SotrMultiError is an error wrapping multiple validation errors returned by
// Sotr.ValidateAll() if the designated constraints aren't met.
type SotrMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SotrMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SotrMultiError) AllErrors() []error { return m }

// SotrValidationError is the validation error returned by Sotr.Validate if the
// designated constraints aren't met.
type SotrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SotrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SotrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SotrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SotrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SotrValidationError) ErrorName() string { return "SotrValidationError" }

// Error satisfies the builtin error interface
func (e SotrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSotr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SotrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SotrValidationError{}

// Validate checks the field values on History with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *History) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on History with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HistoryMultiError, or nil if none found.
func (m *History) ValidateAll() error {
	return m.validate(true)
}

func (m *History) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, HistoryValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, HistoryValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HistoryValidationError{
				field:  "Date",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Field

	// no validation rules for OldValue

	// no validation rules for SotrId

	if len(errors) > 0 {
		return HistoryMultiError(errors)
	}

	return nil
}

// HistoryMultiError is an error wrapping multiple validation errors returned
// by History.ValidateAll() if the designated constraints aren't met.
type HistoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HistoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HistoryMultiError) AllErrors() []error { return m }

// HistoryValidationError is the validation error returned by History.Validate
// if the designated constraints aren't met.
type HistoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HistoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HistoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HistoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HistoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HistoryValidationError) ErrorName() string { return "HistoryValidationError" }

// Error satisfies the builtin error interface
func (e HistoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHistory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HistoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HistoryValidationError{}

// Validate checks the field values on Sotrs with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Sotrs) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Sotrs with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SotrsMultiError, or nil if none found.
func (m *Sotrs) ValidateAll() error {
	return m.validate(true)
}

func (m *Sotrs) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSotrs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SotrsValidationError{
						field:  fmt.Sprintf("Sotrs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SotrsValidationError{
						field:  fmt.Sprintf("Sotrs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SotrsValidationError{
					field:  fmt.Sprintf("Sotrs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SotrsMultiError(errors)
	}

	return nil
}

// SotrsMultiError is an error wrapping multiple validation errors returned by
// Sotrs.ValidateAll() if the designated constraints aren't met.
type SotrsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SotrsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SotrsMultiError) AllErrors() []error { return m }

// SotrsValidationError is the validation error returned by Sotrs.Validate if
// the designated constraints aren't met.
type SotrsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SotrsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SotrsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SotrsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SotrsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SotrsValidationError) ErrorName() string { return "SotrsValidationError" }

// Error satisfies the builtin error interface
func (e SotrsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSotrs.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SotrsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SotrsValidationError{}

// Validate checks the field values on Item with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Item with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ItemMultiError, or nil if none found.
func (m *Item) ValidateAll() error {
	return m.validate(true)
}

func (m *Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Var.(type) {
	case *Item_Dep:
		if v == nil {
			err := ItemValidationError{
				field:  "Var",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDep()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ItemValidationError{
						field:  "Dep",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ItemValidationError{
						field:  "Dep",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDep()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemValidationError{
					field:  "Dep",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Item_Sotr:
		if v == nil {
			err := ItemValidationError{
				field:  "Var",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSotr()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ItemValidationError{
						field:  "Sotr",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ItemValidationError{
						field:  "Sotr",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSotr()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ItemValidationError{
					field:  "Sotr",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ItemMultiError(errors)
	}

	return nil
}

// ItemMultiError is an error wrapping multiple validation errors returned by
// Item.ValidateAll() if the designated constraints aren't met.
type ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ItemMultiError) AllErrors() []error { return m }

// ItemValidationError is the validation error returned by Item.Validate if the
// designated constraints aren't met.
type ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ItemValidationError) ErrorName() string { return "ItemValidationError" }

// Error satisfies the builtin error interface
func (e ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ItemValidationError{}

// Validate checks the field values on HistoryList with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HistoryList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HistoryList with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HistoryListMultiError, or
// nil if none found.
func (m *HistoryList) ValidateAll() error {
	return m.validate(true)
}

func (m *HistoryList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetHistoryList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HistoryListValidationError{
						field:  fmt.Sprintf("HistoryList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HistoryListValidationError{
						field:  fmt.Sprintf("HistoryList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HistoryListValidationError{
					field:  fmt.Sprintf("HistoryList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HistoryListMultiError(errors)
	}

	return nil
}

// HistoryListMultiError is an error wrapping multiple validation errors
// returned by HistoryList.ValidateAll() if the designated constraints aren't met.
type HistoryListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HistoryListMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HistoryListMultiError) AllErrors() []error { return m }

// HistoryListValidationError is the validation error returned by
// HistoryList.Validate if the designated constraints aren't met.
type HistoryListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HistoryListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HistoryListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HistoryListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HistoryListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HistoryListValidationError) ErrorName() string { return "HistoryListValidationError" }

// Error satisfies the builtin error interface
func (e HistoryListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHistoryList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HistoryListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HistoryListValidationError{}

// Validate checks the field values on QueryUpdateSotr with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *QueryUpdateSotr) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryUpdateSotr with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryUpdateSotrMultiError, or nil if none found.
func (m *QueryUpdateSotr) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryUpdateSotr) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSotr()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryUpdateSotrValidationError{
					field:  "Sotr",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryUpdateSotrValidationError{
					field:  "Sotr",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSotr()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryUpdateSotrValidationError{
				field:  "Sotr",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetHistoryList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryUpdateSotrValidationError{
						field:  fmt.Sprintf("HistoryList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryUpdateSotrValidationError{
						field:  fmt.Sprintf("HistoryList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryUpdateSotrValidationError{
					field:  fmt.Sprintf("HistoryList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return QueryUpdateSotrMultiError(errors)
	}

	return nil
}

// QueryUpdateSotrMultiError is an error wrapping multiple validation errors
// returned by QueryUpdateSotr.ValidateAll() if the designated constraints
// aren't met.
type QueryUpdateSotrMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryUpdateSotrMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryUpdateSotrMultiError) AllErrors() []error { return m }

// QueryUpdateSotrValidationError is the validation error returned by
// QueryUpdateSotr.Validate if the designated constraints aren't met.
type QueryUpdateSotrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryUpdateSotrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryUpdateSotrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryUpdateSotrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryUpdateSotrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryUpdateSotrValidationError) ErrorName() string { return "QueryUpdateSotrValidationError" }

// Error satisfies the builtin error interface
func (e QueryUpdateSotrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryUpdateSotr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryUpdateSotrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryUpdateSotrValidationError{}
