// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: stor.proto

package kbv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Item with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Item with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ItemMultiError, or nil if none found.
func (m *Item) ValidateAll() error {
	return m.validate(true)
}

func (m *Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Idr

	// no validation rules for Parent

	// no validation rules for Text

	// no validation rules for Children

	if len(errors) > 0 {
		return ItemMultiError(errors)
	}

	return nil
}

// ItemMultiError is an error wrapping multiple validation errors returned by
// Item.ValidateAll() if the designated constraints aren't met.
type ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ItemMultiError) AllErrors() []error { return m }

// ItemValidationError is the validation error returned by Item.Validate if the
// designated constraints aren't met.
type ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ItemValidationError) ErrorName() string { return "ItemValidationError" }

// Error satisfies the builtin error interface
func (e ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ItemValidationError{}

// Validate checks the field values on Idr with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Idr) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Idr with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in IdrMultiError, or nil if none found.
func (m *Idr) ValidateAll() error {
	return m.validate(true)
}

func (m *Idr) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Idr

	if len(errors) > 0 {
		return IdrMultiError(errors)
	}

	return nil
}

// IdrMultiError is an error wrapping multiple validation errors returned by
// Idr.ValidateAll() if the designated constraints aren't met.
type IdrMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdrMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdrMultiError) AllErrors() []error { return m }

// IdrValidationError is the validation error returned by Idr.Validate if the
// designated constraints aren't met.
type IdrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdrValidationError) ErrorName() string { return "IdrValidationError" }

// Error satisfies the builtin error interface
func (e IdrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdrValidationError{}

// Validate checks the field values on Tabnum with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Tabnum) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Tabnum with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TabnumMultiError, or nil if none found.
func (m *Tabnum) ValidateAll() error {
	return m.validate(true)
}

func (m *Tabnum) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Tabnum

	if len(errors) > 0 {
		return TabnumMultiError(errors)
	}

	return nil
}

// TabnumMultiError is an error wrapping multiple validation errors returned by
// Tabnum.ValidateAll() if the designated constraints aren't met.
type TabnumMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TabnumMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TabnumMultiError) AllErrors() []error { return m }

// TabnumValidationError is the validation error returned by Tabnum.Validate if
// the designated constraints aren't met.
type TabnumValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TabnumValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TabnumValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TabnumValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TabnumValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TabnumValidationError) ErrorName() string { return "TabnumValidationError" }

// Error satisfies the builtin error interface
func (e TabnumValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTabnum.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TabnumValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TabnumValidationError{}

// Validate checks the field values on Fio with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Fio) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Fio with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FioMultiError, or nil if none found.
func (m *Fio) ValidateAll() error {
	return m.validate(true)
}

func (m *Fio) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Fio

	if len(errors) > 0 {
		return FioMultiError(errors)
	}

	return nil
}

// FioMultiError is an error wrapping multiple validation errors returned by
// Fio.ValidateAll() if the designated constraints aren't met.
type FioMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FioMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FioMultiError) AllErrors() []error { return m }

// FioValidationError is the validation error returned by Fio.Validate if the
// designated constraints aren't met.
type FioValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FioValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FioValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FioValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FioValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FioValidationError) ErrorName() string { return "FioValidationError" }

// Error satisfies the builtin error interface
func (e FioValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFio.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FioValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FioValidationError{}

// Validate checks the field values on Sotr with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Sotr) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Sotr with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SotrMultiError, or nil if none found.
func (m *Sotr) ValidateAll() error {
	return m.validate(true)
}

func (m *Sotr) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Idr

	// no validation rules for Tabnum

	// no validation rules for Name

	// no validation rules for MidName

	// no validation rules for Phone

	// no validation rules for Mobile

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = SotrValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Avatar

	// no validation rules for Grade

	// no validation rules for Children

	// no validation rules for ParentId

	for idx, item := range m.GetHist() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SotrValidationError{
						field:  fmt.Sprintf("Hist[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SotrValidationError{
						field:  fmt.Sprintf("Hist[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SotrValidationError{
					field:  fmt.Sprintf("Hist[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SotrMultiError(errors)
	}

	return nil
}

func (m *Sotr) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *Sotr) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// SotrMultiError is an error wrapping multiple validation errors returned by
// Sotr.ValidateAll() if the designated constraints aren't met.
type SotrMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SotrMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SotrMultiError) AllErrors() []error { return m }

// SotrValidationError is the validation error returned by Sotr.Validate if the
// designated constraints aren't met.
type SotrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SotrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SotrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SotrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SotrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SotrValidationError) ErrorName() string { return "SotrValidationError" }

// Error satisfies the builtin error interface
func (e SotrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSotr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SotrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SotrValidationError{}

// Validate checks the field values on History with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *History) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on History with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HistoryMultiError, or nil if none found.
func (m *History) ValidateAll() error {
	return m.validate(true)
}

func (m *History) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, HistoryValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, HistoryValidationError{
					field:  "Date",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HistoryValidationError{
				field:  "Date",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Field

	// no validation rules for OldValue

	if len(errors) > 0 {
		return HistoryMultiError(errors)
	}

	return nil
}

// HistoryMultiError is an error wrapping multiple validation errors returned
// by History.ValidateAll() if the designated constraints aren't met.
type HistoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HistoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HistoryMultiError) AllErrors() []error { return m }

// HistoryValidationError is the validation error returned by History.Validate
// if the designated constraints aren't met.
type HistoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HistoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HistoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HistoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HistoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HistoryValidationError) ErrorName() string { return "HistoryValidationError" }

// Error satisfies the builtin error interface
func (e HistoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHistory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HistoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HistoryValidationError{}
