//
// Kbempgo Stor API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: stor.proto

package kbv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Idr           string                 `protobuf:"bytes,2,opt,name=idr,proto3" json:"idr,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Children      bool                   `protobuf:"varint,5,opt,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_stor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetIdr() string {
	if x != nil {
		return x.Idr
	}
	return ""
}

func (x *Item) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Item) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Item) GetChildren() bool {
	if x != nil {
		return x.Children
	}
	return false
}

type Idr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idr           string                 `protobuf:"bytes,1,opt,name=idr,proto3" json:"idr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idr) Reset() {
	*x = Idr{}
	mi := &file_stor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idr) ProtoMessage() {}

func (x *Idr) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idr.ProtoReflect.Descriptor instead.
func (*Idr) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{1}
}

func (x *Idr) GetIdr() string {
	if x != nil {
		return x.Idr
	}
	return ""
}

type Tabnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tabnum        string                 `protobuf:"bytes,1,opt,name=tabnum,proto3" json:"tabnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tabnum) Reset() {
	*x = Tabnum{}
	mi := &file_stor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tabnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tabnum) ProtoMessage() {}

func (x *Tabnum) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tabnum.ProtoReflect.Descriptor instead.
func (*Tabnum) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{2}
}

func (x *Tabnum) GetTabnum() string {
	if x != nil {
		return x.Tabnum
	}
	return ""
}

type Fio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fio           string                 `protobuf:"bytes,1,opt,name=fio,proto3" json:"fio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fio) Reset() {
	*x = Fio{}
	mi := &file_stor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fio) ProtoMessage() {}

func (x *Fio) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fio.ProtoReflect.Descriptor instead.
func (*Fio) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{3}
}

func (x *Fio) GetFio() string {
	if x != nil {
		return x.Fio
	}
	return ""
}

type Sotr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Idr           string                 `protobuf:"bytes,2,opt,name=idr,proto3" json:"idr,omitempty"`
	Tabnum        string                 `protobuf:"bytes,3,opt,name=tabnum,proto3" json:"tabnum,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	MidName       string                 `protobuf:"bytes,5,opt,name=mid_name,json=midName,proto3" json:"mid_name,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Mobile        string                 `protobuf:"bytes,7,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Grade         string                 `protobuf:"bytes,10,opt,name=grade,proto3" json:"grade,omitempty"`
	Children      bool                   `protobuf:"varint,11,opt,name=children,proto3" json:"children,omitempty"`
	ParentId      string                 `protobuf:"bytes,12,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Hist          []*History             `protobuf:"bytes,13,rep,name=hist,proto3" json:"hist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sotr) Reset() {
	*x = Sotr{}
	mi := &file_stor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sotr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sotr) ProtoMessage() {}

func (x *Sotr) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sotr.ProtoReflect.Descriptor instead.
func (*Sotr) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{4}
}

func (x *Sotr) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sotr) GetIdr() string {
	if x != nil {
		return x.Idr
	}
	return ""
}

func (x *Sotr) GetTabnum() string {
	if x != nil {
		return x.Tabnum
	}
	return ""
}

func (x *Sotr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sotr) GetMidName() string {
	if x != nil {
		return x.MidName
	}
	return ""
}

func (x *Sotr) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Sotr) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Sotr) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Sotr) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Sotr) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *Sotr) GetChildren() bool {
	if x != nil {
		return x.Children
	}
	return false
}

func (x *Sotr) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Sotr) GetHist() []*History {
	if x != nil {
		return x.Hist
	}
	return nil
}

type History struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	OldValue      string                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_stor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{5}
}

func (x *History) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *History) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *History) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

var File_stor_proto protoreflect.FileDescriptor

const file_stor_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"stor.proto\x12\x05kb.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"p\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03idr\x18\x02 \x01(\tR\x03idr\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1a\n" +
	"\bchildren\x18\x05 \x01(\bR\bchildren\"\x17\n" +
	"\x03Idr\x12\x10\n" +
	"\x03idr\x18\x01 \x01(\tR\x03idr\" \n" +
	"\x06Tabnum\x12\x16\n" +
	"\x06tabnum\x18\x01 \x01(\tR\x06tabnum\"\x17\n" +
	"\x03Fio\x12\x10\n" +
	"\x03fio\x18\x01 \x01(\tR\x03fio\"\xc7\x02\n" +
	"\x04Sotr\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03idr\x18\x02 \x01(\tR\x03idr\x12\x16\n" +
	"\x06tabnum\x18\x03 \x01(\tR\x06tabnum\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x19\n" +
	"\bmid_name\x18\x05 \x01(\tR\amidName\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06mobile\x18\a \x01(\tR\x06mobile\x12\x1d\n" +
	"\x05email\x18\b \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatar\x12\x14\n" +
	"\x05grade\x18\n" +
	" \x01(\tR\x05grade\x12\x1a\n" +
	"\bchildren\x18\v \x01(\bR\bchildren\x12\x1b\n" +
	"\tparent_id\x18\f \x01(\tR\bparentId\x12\"\n" +
	"\x04hist\x18\r \x03(\v2\x0e.kb.v1.HistoryR\x04hist\"l\n" +
	"\aHistory\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\tR\boldValue2\xeb\x02\n" +
	"\x04Stor\x12C\n" +
	"\bGetDepBy\x12\n" +
	".kb.v1.Idr\x1a\v.kb.v1.Item\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/stor/v1/dep/{idr}\x12U\n" +
	"\x0fGetSotrByTabnum\x12\r.kb.v1.Tabnum\x1a\v.kb.v1.Sotr\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/stor/v1/employee/{tabnum}\x12L\n" +
	"\fGetSotrByFio\x12\n" +
	".kb.v1.Fio\x1a\v.kb.v1.Sotr\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/stor/v1/employee/{fio}\x12y\n" +
	"\x04Save\x12\v.kb.v1.Item\x1a\x16.google.protobuf.Empty\"L\x82\xd3\xe4\x93\x02F:\x01*Z\x16:\x01*\x1a\x11/api/stor/v1/saveZ\x16:\x01*2\x11/api/stor/v1/save\"\x11/api/stor/v1/saveB-Z+github.com/mioxin/kbempgo/api/kbemp/v1;kbv1b\x06proto3"

var (
	file_stor_proto_rawDescOnce sync.Once
	file_stor_proto_rawDescData []byte
)

func file_stor_proto_rawDescGZIP() []byte {
	file_stor_proto_rawDescOnce.Do(func() {
		file_stor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stor_proto_rawDesc), len(file_stor_proto_rawDesc)))
	})
	return file_stor_proto_rawDescData
}

var file_stor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stor_proto_goTypes = []any{
	(*Item)(nil),                  // 0: kb.v1.Item
	(*Idr)(nil),                   // 1: kb.v1.Idr
	(*Tabnum)(nil),                // 2: kb.v1.Tabnum
	(*Fio)(nil),                   // 3: kb.v1.Fio
	(*Sotr)(nil),                  // 4: kb.v1.Sotr
	(*History)(nil),               // 5: kb.v1.History
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_stor_proto_depIdxs = []int32{
	5, // 0: kb.v1.Sotr.hist:type_name -> kb.v1.History
	6, // 1: kb.v1.History.date:type_name -> google.protobuf.Timestamp
	1, // 2: kb.v1.Stor.GetDepBy:input_type -> kb.v1.Idr
	2, // 3: kb.v1.Stor.GetSotrByTabnum:input_type -> kb.v1.Tabnum
	3, // 4: kb.v1.Stor.GetSotrByFio:input_type -> kb.v1.Fio
	0, // 5: kb.v1.Stor.Save:input_type -> kb.v1.Item
	0, // 6: kb.v1.Stor.GetDepBy:output_type -> kb.v1.Item
	4, // 7: kb.v1.Stor.GetSotrByTabnum:output_type -> kb.v1.Sotr
	4, // 8: kb.v1.Stor.GetSotrByFio:output_type -> kb.v1.Sotr
	7, // 9: kb.v1.Stor.Save:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stor_proto_init() }
func file_stor_proto_init() {
	if File_stor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stor_proto_rawDesc), len(file_stor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stor_proto_goTypes,
		DependencyIndexes: file_stor_proto_depIdxs,
		MessageInfos:      file_stor_proto_msgTypes,
	}.Build()
	File_stor_proto = out.File
	file_stor_proto_goTypes = nil
	file_stor_proto_depIdxs = nil
}
