//
// Kbempgo Stor API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: stor.proto

package kbv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepRequest_DBField int32

const (
	DepRequest_NONE   DepRequest_DBField = 0
	DepRequest_IDR    DepRequest_DBField = 1
	DepRequest_PARENT DepRequest_DBField = 4
)

// Enum value maps for DepRequest_DBField.
var (
	DepRequest_DBField_name = map[int32]string{
		0: "NONE",
		1: "IDR",
		4: "PARENT",
	}
	DepRequest_DBField_value = map[string]int32{
		"NONE":   0,
		"IDR":    1,
		"PARENT": 4,
	}
)

func (x DepRequest_DBField) Enum() *DepRequest_DBField {
	p := new(DepRequest_DBField)
	*p = x
	return p
}

func (x DepRequest_DBField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepRequest_DBField) Descriptor() protoreflect.EnumDescriptor {
	return file_stor_proto_enumTypes[0].Descriptor()
}

func (DepRequest_DBField) Type() protoreflect.EnumType {
	return &file_stor_proto_enumTypes[0]
}

func (x DepRequest_DBField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepRequest_DBField.Descriptor instead.
func (DepRequest_DBField) EnumDescriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{2, 0}
}

type SotrRequest_DBField int32

const (
	SotrRequest_NONE   SotrRequest_DBField = 0
	SotrRequest_MOBILE SotrRequest_DBField = 1
	SotrRequest_FIO    SotrRequest_DBField = 2
	SotrRequest_TABNUM SotrRequest_DBField = 3
	SotrRequest_IDR    SotrRequest_DBField = 4
)

// Enum value maps for SotrRequest_DBField.
var (
	SotrRequest_DBField_name = map[int32]string{
		0: "NONE",
		1: "MOBILE",
		2: "FIO",
		3: "TABNUM",
		4: "IDR",
	}
	SotrRequest_DBField_value = map[string]int32{
		"NONE":   0,
		"MOBILE": 1,
		"FIO":    2,
		"TABNUM": 3,
		"IDR":    4,
	}
)

func (x SotrRequest_DBField) Enum() *SotrRequest_DBField {
	p := new(SotrRequest_DBField)
	*p = x
	return p
}

func (x SotrRequest_DBField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SotrRequest_DBField) Descriptor() protoreflect.EnumDescriptor {
	return file_stor_proto_enumTypes[1].Descriptor()
}

func (SotrRequest_DBField) Type() protoreflect.EnumType {
	return &file_stor_proto_enumTypes[1]
}

func (x SotrRequest_DBField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SotrRequest_DBField.Descriptor instead.
func (SotrRequest_DBField) EnumDescriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{3, 0}
}

type Dep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Idr           string                 `protobuf:"bytes,2,opt,name=idr,proto3" json:"idr,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Children      bool                   `protobuf:"varint,5,opt,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dep) Reset() {
	*x = Dep{}
	mi := &file_stor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dep) ProtoMessage() {}

func (x *Dep) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dep.ProtoReflect.Descriptor instead.
func (*Dep) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{0}
}

func (x *Dep) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dep) GetIdr() string {
	if x != nil {
		return x.Idr
	}
	return ""
}

func (x *Dep) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Dep) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Dep) GetChildren() bool {
	if x != nil {
		return x.Children
	}
	return false
}

type DepsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deps          []*Dep                 `protobuf:"bytes,1,rep,name=deps,proto3" json:"deps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepsResponse) Reset() {
	*x = DepsResponse{}
	mi := &file_stor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepsResponse) ProtoMessage() {}

func (x *DepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepsResponse.ProtoReflect.Descriptor instead.
func (*DepsResponse) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{1}
}

func (x *DepsResponse) GetDeps() []*Dep {
	if x != nil {
		return x.Deps
	}
	return nil
}

type DepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           string                 `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	Field         DepRequest_DBField     `protobuf:"varint,2,opt,name=field,proto3,enum=kb.v1.DepRequest_DBField" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepRequest) Reset() {
	*x = DepRequest{}
	mi := &file_stor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepRequest) ProtoMessage() {}

func (x *DepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepRequest.ProtoReflect.Descriptor instead.
func (*DepRequest) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{2}
}

func (x *DepRequest) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *DepRequest) GetField() DepRequest_DBField {
	if x != nil {
		return x.Field
	}
	return DepRequest_NONE
}

type SotrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           string                 `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	Field         SotrRequest_DBField    `protobuf:"varint,2,opt,name=field,proto3,enum=kb.v1.SotrRequest_DBField" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SotrRequest) Reset() {
	*x = SotrRequest{}
	mi := &file_stor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SotrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SotrRequest) ProtoMessage() {}

func (x *SotrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SotrRequest.ProtoReflect.Descriptor instead.
func (*SotrRequest) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{3}
}

func (x *SotrRequest) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *SotrRequest) GetField() SotrRequest_DBField {
	if x != nil {
		return x.Field
	}
	return SotrRequest_NONE
}

type HistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SotrId        string                 `protobuf:"bytes,1,opt,name=sotr_id,json=sotrId,proto3" json:"sotr_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistRequest) Reset() {
	*x = HistRequest{}
	mi := &file_stor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistRequest) ProtoMessage() {}

func (x *HistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistRequest.ProtoReflect.Descriptor instead.
func (*HistRequest) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{4}
}

func (x *HistRequest) GetSotrId() string {
	if x != nil {
		return x.SotrId
	}
	return ""
}

type Sotr struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Idr      string                 `protobuf:"bytes,2,opt,name=idr,proto3" json:"idr,omitempty"`
	Tabnum   string                 `protobuf:"bytes,3,opt,name=tabnum,proto3" json:"tabnum,omitempty"`
	Name     string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	MidName  string                 `protobuf:"bytes,5,opt,name=mid_name,json=midName,proto3" json:"mid_name,omitempty"`
	Phone    []string               `protobuf:"bytes,6,rep,name=phone,proto3" json:"phone,omitempty"`
	Mobile   []string               `protobuf:"bytes,7,rep,name=mobile,proto3" json:"mobile,omitempty"`
	Email    string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Avatar   string                 `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Grade    string                 `protobuf:"bytes,10,opt,name=grade,proto3" json:"grade,omitempty"`
	Children bool                   `protobuf:"varint,11,opt,name=children,proto3" json:"children,omitempty"`
	ParentId string                 `protobuf:"bytes,12,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// repeated History hist = 13[ json_name = "history" ];
	Date          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sotr) Reset() {
	*x = Sotr{}
	mi := &file_stor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sotr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sotr) ProtoMessage() {}

func (x *Sotr) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sotr.ProtoReflect.Descriptor instead.
func (*Sotr) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{5}
}

func (x *Sotr) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sotr) GetIdr() string {
	if x != nil {
		return x.Idr
	}
	return ""
}

func (x *Sotr) GetTabnum() string {
	if x != nil {
		return x.Tabnum
	}
	return ""
}

func (x *Sotr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sotr) GetMidName() string {
	if x != nil {
		return x.MidName
	}
	return ""
}

func (x *Sotr) GetPhone() []string {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *Sotr) GetMobile() []string {
	if x != nil {
		return x.Mobile
	}
	return nil
}

func (x *Sotr) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Sotr) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Sotr) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *Sotr) GetChildren() bool {
	if x != nil {
		return x.Children
	}
	return false
}

func (x *Sotr) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Sotr) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type History struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	OldValue      string                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	SotrId        uint64                 `protobuf:"varint,4,opt,name=sotr_id,json=sotr_uid,proto3" json:"sotr_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_stor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{6}
}

func (x *History) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *History) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *History) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *History) GetSotrId() uint64 {
	if x != nil {
		return x.SotrId
	}
	return 0
}

type SotrsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sotrs         []*Sotr                `protobuf:"bytes,1,rep,name=sotrs,proto3" json:"sotrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SotrsResponse) Reset() {
	*x = SotrsResponse{}
	mi := &file_stor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SotrsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SotrsResponse) ProtoMessage() {}

func (x *SotrsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SotrsResponse.ProtoReflect.Descriptor instead.
func (*SotrsResponse) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{7}
}

func (x *SotrsResponse) GetSotrs() []*Sotr {
	if x != nil {
		return x.Sotrs
	}
	return nil
}

type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Var:
	//
	//	*Item_Dep
	//	*Item_Sotr
	Var           isItem_Var `protobuf_oneof:"var"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_stor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{8}
}

func (x *Item) GetVar() isItem_Var {
	if x != nil {
		return x.Var
	}
	return nil
}

func (x *Item) GetDep() *Dep {
	if x != nil {
		if x, ok := x.Var.(*Item_Dep); ok {
			return x.Dep
		}
	}
	return nil
}

func (x *Item) GetSotr() *Sotr {
	if x != nil {
		if x, ok := x.Var.(*Item_Sotr); ok {
			return x.Sotr
		}
	}
	return nil
}

type isItem_Var interface {
	isItem_Var()
}

type Item_Dep struct {
	Dep *Dep `protobuf:"bytes,1,opt,name=dep,proto3,oneof"`
}

type Item_Sotr struct {
	Sotr *Sotr `protobuf:"bytes,2,opt,name=sotr,proto3,oneof"`
}

func (*Item_Dep) isItem_Var() {}

func (*Item_Sotr) isItem_Var() {}

type HistoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryList   []*History             `protobuf:"bytes,1,rep,name=history_list,json=historyList,proto3" json:"history_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryListResponse) Reset() {
	*x = HistoryListResponse{}
	mi := &file_stor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryListResponse) ProtoMessage() {}

func (x *HistoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryListResponse.ProtoReflect.Descriptor instead.
func (*HistoryListResponse) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{9}
}

func (x *HistoryListResponse) GetHistoryList() []*History {
	if x != nil {
		return x.HistoryList
	}
	return nil
}

type UpdateSotrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sotr          *Sotr                  `protobuf:"bytes,1,opt,name=sotr,proto3" json:"sotr,omitempty"`
	HistoryList   []*History             `protobuf:"bytes,2,rep,name=history_list,json=historyList,proto3" json:"history_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSotrRequest) Reset() {
	*x = UpdateSotrRequest{}
	mi := &file_stor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSotrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSotrRequest) ProtoMessage() {}

func (x *UpdateSotrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSotrRequest.ProtoReflect.Descriptor instead.
func (*UpdateSotrRequest) Descriptor() ([]byte, []int) {
	return file_stor_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSotrRequest) GetSotr() *Sotr {
	if x != nil {
		return x.Sotr
	}
	return nil
}

func (x *UpdateSotrRequest) GetHistoryList() []*History {
	if x != nil {
		return x.HistoryList
	}
	return nil
}

var File_stor_proto protoreflect.FileDescriptor

const file_stor_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"stor.proto\x12\x05kb.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"o\n" +
	"\x03Dep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03idr\x18\x02 \x01(\tR\x03idr\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1a\n" +
	"\bchildren\x18\x05 \x01(\bR\bchildren\".\n" +
	"\fDepsResponse\x12\x1e\n" +
	"\x04deps\x18\x01 \x03(\v2\n" +
	".kb.v1.DepR\x04deps\"y\n" +
	"\n" +
	"DepRequest\x12\x10\n" +
	"\x03str\x18\x01 \x01(\tR\x03str\x12/\n" +
	"\x05field\x18\x02 \x01(\x0e2\x19.kb.v1.DepRequest.DBFieldR\x05field\"(\n" +
	"\aDBField\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03IDR\x10\x01\x12\n" +
	"\n" +
	"\x06PARENT\x10\x04\"\x90\x01\n" +
	"\vSotrRequest\x12\x10\n" +
	"\x03str\x18\x01 \x01(\tR\x03str\x120\n" +
	"\x05field\x18\x02 \x01(\x0e2\x1a.kb.v1.SotrRequest.DBFieldR\x05field\"=\n" +
	"\aDBField\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06MOBILE\x10\x01\x12\a\n" +
	"\x03FIO\x10\x02\x12\n" +
	"\n" +
	"\x06TABNUM\x10\x03\x12\a\n" +
	"\x03IDR\x10\x04\"&\n" +
	"\vHistRequest\x12\x17\n" +
	"\asotr_id\x18\x01 \x01(\tR\x06sotrId\"\xd6\x02\n" +
	"\x04Sotr\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03idr\x18\x02 \x01(\tR\x03idr\x12\x16\n" +
	"\x06tabnum\x18\x03 \x01(\tR\x06tabnum\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x19\n" +
	"\bmid_name\x18\x05 \x01(\tR\amidName\x12\x14\n" +
	"\x05phone\x18\x06 \x03(\tR\x05phone\x12\x16\n" +
	"\x06mobile\x18\a \x03(\tR\x06mobile\x12 \n" +
	"\x05email\x18\b \x01(\tB\n" +
	"\xfaB\ar\x05\xd0\x01\x01`\x01R\x05email\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatar\x12\x14\n" +
	"\x05grade\x18\n" +
	" \x01(\tR\x05grade\x12\x1a\n" +
	"\bchildren\x18\v \x01(\bR\bchildren\x12\x1b\n" +
	"\tparent_id\x18\f \x01(\tR\bparentId\x12.\n" +
	"\x04date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\x87\x01\n" +
	"\aHistory\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\tR\boldValue\x12\x19\n" +
	"\asotr_id\x18\x04 \x01(\x04R\bsotr_uid\"2\n" +
	"\rSotrsResponse\x12!\n" +
	"\x05sotrs\x18\x01 \x03(\v2\v.kb.v1.SotrR\x05sotrs\"P\n" +
	"\x04Item\x12\x1e\n" +
	"\x03dep\x18\x01 \x01(\v2\n" +
	".kb.v1.DepH\x00R\x03dep\x12!\n" +
	"\x04sotr\x18\x02 \x01(\v2\v.kb.v1.SotrH\x00R\x04sotrB\x05\n" +
	"\x03var\"H\n" +
	"\x13HistoryListResponse\x121\n" +
	"\fhistory_list\x18\x01 \x03(\v2\x0e.kb.v1.HistoryR\vhistoryList\"g\n" +
	"\x11UpdateSotrRequest\x12\x1f\n" +
	"\x04sotr\x18\x01 \x01(\v2\v.kb.v1.SotrR\x04sotr\x121\n" +
	"\fhistory_list\x18\x02 \x03(\v2\x0e.kb.v1.HistoryR\vhistoryList2\xc6\x04\n" +
	"\aStorAPI\x12[\n" +
	"\tGetDepsBy\x12\x11.kb.v1.DepRequest\x1a\x13.kb.v1.DepsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/stor/v1/dep/{field}/{str}\x12c\n" +
	"\n" +
	"GetSotrsBy\x12\x12.kb.v1.SotrRequest\x1a\x14.kb.v1.SotrsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/stor/v1/employee/{field}/{str}\x12V\n" +
	"\x05Flush\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/stor/v1/flush\x12a\n" +
	"\x04Save\x12\v.kb.v1.Item\x1a\x16.google.protobuf.Empty\"4\x82\xd3\xe4\x93\x02.:\x01*Z\x16:\x01*\x1a\x11/api/stor/v1/save\"\x11/api/stor/v1/save\x12X\n" +
	"\x06Update\x12\x18.kb.v1.UpdateSotrRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/api/stor/v1/save\x12d\n" +
	"\n" +
	"GetHistory\x12\x12.kb.v1.HistRequest\x1a\x1a.kb.v1.HistoryListResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/stor/v1/history/{sotr_id}B-Z+github.com/mioxin/kbempgo/api/kbemp/v1;kbv1b\x06proto3"

var (
	file_stor_proto_rawDescOnce sync.Once
	file_stor_proto_rawDescData []byte
)

func file_stor_proto_rawDescGZIP() []byte {
	file_stor_proto_rawDescOnce.Do(func() {
		file_stor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stor_proto_rawDesc), len(file_stor_proto_rawDesc)))
	})
	return file_stor_proto_rawDescData
}

var file_stor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_stor_proto_goTypes = []any{
	(DepRequest_DBField)(0),       // 0: kb.v1.DepRequest.DBField
	(SotrRequest_DBField)(0),      // 1: kb.v1.SotrRequest.DBField
	(*Dep)(nil),                   // 2: kb.v1.Dep
	(*DepsResponse)(nil),          // 3: kb.v1.DepsResponse
	(*DepRequest)(nil),            // 4: kb.v1.DepRequest
	(*SotrRequest)(nil),           // 5: kb.v1.SotrRequest
	(*HistRequest)(nil),           // 6: kb.v1.HistRequest
	(*Sotr)(nil),                  // 7: kb.v1.Sotr
	(*History)(nil),               // 8: kb.v1.History
	(*SotrsResponse)(nil),         // 9: kb.v1.SotrsResponse
	(*Item)(nil),                  // 10: kb.v1.Item
	(*HistoryListResponse)(nil),   // 11: kb.v1.HistoryListResponse
	(*UpdateSotrRequest)(nil),     // 12: kb.v1.UpdateSotrRequest
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_stor_proto_depIdxs = []int32{
	2,  // 0: kb.v1.DepsResponse.deps:type_name -> kb.v1.Dep
	0,  // 1: kb.v1.DepRequest.field:type_name -> kb.v1.DepRequest.DBField
	1,  // 2: kb.v1.SotrRequest.field:type_name -> kb.v1.SotrRequest.DBField
	13, // 3: kb.v1.Sotr.date:type_name -> google.protobuf.Timestamp
	13, // 4: kb.v1.History.date:type_name -> google.protobuf.Timestamp
	7,  // 5: kb.v1.SotrsResponse.sotrs:type_name -> kb.v1.Sotr
	2,  // 6: kb.v1.Item.dep:type_name -> kb.v1.Dep
	7,  // 7: kb.v1.Item.sotr:type_name -> kb.v1.Sotr
	8,  // 8: kb.v1.HistoryListResponse.history_list:type_name -> kb.v1.History
	7,  // 9: kb.v1.UpdateSotrRequest.sotr:type_name -> kb.v1.Sotr
	8,  // 10: kb.v1.UpdateSotrRequest.history_list:type_name -> kb.v1.History
	4,  // 11: kb.v1.StorAPI.GetDepsBy:input_type -> kb.v1.DepRequest
	5,  // 12: kb.v1.StorAPI.GetSotrsBy:input_type -> kb.v1.SotrRequest
	14, // 13: kb.v1.StorAPI.Flush:input_type -> google.protobuf.Empty
	10, // 14: kb.v1.StorAPI.Save:input_type -> kb.v1.Item
	12, // 15: kb.v1.StorAPI.Update:input_type -> kb.v1.UpdateSotrRequest
	6,  // 16: kb.v1.StorAPI.GetHistory:input_type -> kb.v1.HistRequest
	3,  // 17: kb.v1.StorAPI.GetDepsBy:output_type -> kb.v1.DepsResponse
	9,  // 18: kb.v1.StorAPI.GetSotrsBy:output_type -> kb.v1.SotrsResponse
	14, // 19: kb.v1.StorAPI.Flush:output_type -> google.protobuf.Empty
	14, // 20: kb.v1.StorAPI.Save:output_type -> google.protobuf.Empty
	14, // 21: kb.v1.StorAPI.Update:output_type -> google.protobuf.Empty
	11, // 22: kb.v1.StorAPI.GetHistory:output_type -> kb.v1.HistoryListResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_stor_proto_init() }
func file_stor_proto_init() {
	if File_stor_proto != nil {
		return
	}
	file_stor_proto_msgTypes[8].OneofWrappers = []any{
		(*Item_Dep)(nil),
		(*Item_Sotr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stor_proto_rawDesc), len(file_stor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stor_proto_goTypes,
		DependencyIndexes: file_stor_proto_depIdxs,
		EnumInfos:         file_stor_proto_enumTypes,
		MessageInfos:      file_stor_proto_msgTypes,
	}.Build()
	File_stor_proto = out.File
	file_stor_proto_goTypes = nil
	file_stor_proto_depIdxs = nil
}
